### ISSUE TITLE
Upgrade TF version

### ISSUE THREAD

**Issue by a-maci** [qinyao-he/bit-rnn#1]
Not an issue.
 Do you have any plans to upgrade this code base to use latest TF APIs? 

Currently this code base uses TF 0.9 which requires CUDA 7.5 and there isnt a CUDA 7.5 supported on Ubuntu 16.04.

**Comment by qinyao-he** [comment]
Yes，but maybe somedays later when I have time. I'm currently on vacation,
Chinese lunar new year. : )

If you are interested, pull requests are well come, and I think there isn't
too much work to do.

Best regard.
a-maci <notifications@github.com>于2017年1月31日 周二04:10写道：

**Comment by qinyao-he** [comment]
https://github.com/hqythu/bit-rnn/issues/2
