### ISSUE TITLE
tensorflow v1.8.0

### ISSUE THREAD

**Issue by qinyao-he** [qinyao-he/bit-rnn#5]

**Comment by qinyao-he** [comment]
How can we stop hacking internal api of tensorflow?

**Comment by ppwwyyxx** [comment]
居然没弃疗？…
连着rnn的loop部分自己写了总是可以的

**Comment by qinyao-he** [comment]
我突然想起来在tf1.8上跑了一下直接就挂了所以……

**Comment by kaierlong** [comment]
我修改了几处代码，可以在1.8.0上跑

**Comment by qinyao-he** [comment]
@kaierlong Great！可以提一个pull request给我吗？

**Comment by kaierlong** [comment]
@qinyao-he 给你提交了一个pull request，你审核一下。
